apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis-cache
spec:
  dnsNames:
  - whatever-dns-names.com
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
  privateKey:
    rotationPolicy: Always
  secretName: redis-tls
