apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: redis
  namespace: redis
  releaseName: redis
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesFile: ./values.yaml
  version: 20.2.1
resources:
- config-map-lets-encrypt-root-ca.yaml
- certificate-redis-tls.yaml
